/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lelang.frontend.dashboard;

import java.awt.event.ActionListener;
import java.awt.Color;

/**
 *
 * @author hunter
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());
    /**
     * Creates new form DashboardForm
     */
    
    Color DefaultColor, ClickedColor;
    
    public DashboardForm() {
        initComponents();
        DefaultColor = new Color(255,255,255);
        ClickedColor = new Color(30, 144, 255);
        
        DashboardMenu.setBackground(DefaultColor);
        BarangMenu.setBackground(DefaultColor);
        LelangMenu.setBackground(DefaultColor);
    }
    
    public void addLogoutListener(ActionListener listener) {
        btnLogout.addActionListener(listener);
    }
    
    public void addBarangMenuMousePressedListener(ActionListener listener) {
        
    }
    public void setUserData(String name, String email, String role) {
        nameText.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nameText = new javax.swing.JLabel();
        nameText1 = new javax.swing.JLabel();
        nameText2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        DashboardMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BarangMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LelangMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameText.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 0, 0));
        nameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameText.setText("Nama");

        nameText1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameText1.setForeground(new java.awt.Color(0, 0, 0));
        nameText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameText1.setText("Dashboard Lelang Online");

        nameText2.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        nameText2.setForeground(new java.awt.Color(0, 0, 0));
        nameText2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameText2.setText("Created by Muhammad Alfaridzi. Github : alf4ridzi");

        btnLogout.setIcon(new javax.swing.ImageIcon("/Users/alfaridzi/dev/lelang-online/frontend/src/main/resources/images/icons8-logout-48.png")); // NOI18N
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardMenu.setBackground(new java.awt.Color(255, 255, 255));
        DashboardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboardMenuMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/alfaridzi/dev/lelang-online/frontend/src/main/resources/images/icons8-dashboard-24.png")); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout DashboardMenuLayout = new javax.swing.GroupLayout(DashboardMenu);
        DashboardMenu.setLayout(DashboardMenuLayout);
        DashboardMenuLayout.setHorizontalGroup(
            DashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        DashboardMenuLayout.setVerticalGroup(
            DashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(DashboardMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 50));

        BarangMenu.setBackground(new java.awt.Color(255, 255, 255));
        BarangMenu.setPreferredSize(new java.awt.Dimension(149, 50));
        BarangMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarangMenuMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-box-24.png"))); // NOI18N
        jLabel3.setText("Barang");

        javax.swing.GroupLayout BarangMenuLayout = new javax.swing.GroupLayout(BarangMenu);
        BarangMenu.setLayout(BarangMenuLayout);
        BarangMenuLayout.setHorizontalGroup(
            BarangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangMenuLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        BarangMenuLayout.setVerticalGroup(
            BarangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(BarangMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, -1));

        LelangMenu.setBackground(new java.awt.Color(255, 255, 255));
        LelangMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LelangMenuMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/alfaridzi/dev/lelang-online/frontend/src/main/resources/images/icons8-auction-24.png")); // NOI18N
        jLabel7.setText("Lelang");

        javax.swing.GroupLayout LelangMenuLayout = new javax.swing.GroupLayout(LelangMenu);
        LelangMenu.setLayout(LelangMenuLayout);
        LelangMenuLayout.setHorizontalGroup(
            LelangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(LelangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        LelangMenuLayout.setVerticalGroup(
            LelangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(LelangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LelangMenuLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(LelangMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 50));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("© 2025. M.Alfaridzi");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 140, 450));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Di aplikasi lelang");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Selamat Datang");

        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 660, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void DashboardMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMenuMousePressed
        // TODO add your handling code here:
        DashboardMenu.setBackground(ClickedColor);
        BarangMenu.setBackground(DefaultColor);
        LelangMenu.setBackground(DefaultColor);
        
        DashboardUser dash = new DashboardUser();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dash).setVisible(true);
    }//GEN-LAST:event_DashboardMenuMousePressed

    private void LelangMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LelangMenuMousePressed
        // TODO add your handling code here:
        DashboardMenu.setBackground(DefaultColor);
        BarangMenu.setBackground(DefaultColor);
        LelangMenu.setBackground(ClickedColor);
       
       LelangForm lelang = new LelangForm();
       jDesktopPane1.removeAll();
       jDesktopPane1.add(lelang).setVisible(true);
    }//GEN-LAST:event_LelangMenuMousePressed

    private void BarangMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMenuMousePressed
        // TODO add your handling code here:
        DashboardMenu.setBackground(DefaultColor);
        BarangMenu.setBackground(ClickedColor);
        LelangMenu.setBackground(DefaultColor);
        
        BarangForm formBarang = new BarangForm();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(formBarang).setVisible(true);
    }//GEN-LAST:event_BarangMenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarangMenu;
    private javax.swing.JPanel DashboardMenu;
    private javax.swing.JPanel LelangMenu;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nameText1;
    private javax.swing.JLabel nameText2;
    // End of variables declaration//GEN-END:variables
}
