/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.lelang.frontend.dashboard;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author alfaridzi
 */
public class LelangForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form LelangForm
     */
    private Lelang lelang;
    private Lib lib;
    private DefaultTableModel LelangTable;
    
    public LelangForm() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        this.lelang = new Lelang();
        this.lib = new Lib();
        this.LelangTable = (DefaultTableModel) auctionTable.getModel();
        
        loadLelang();
    }
    
    private int getSelectedID() {
        int row = auctionTable.getSelectedRow();
        if (row == -1) {
            return -1;
        }
        
        Object value = auctionTable.getValueAt(row, 0);
        return Integer.valueOf(value.toString());
    }
    
    private String getSelectedName() {
        int row = auctionTable.getSelectedRow();
        if (row == -1) {
            return "";
        }
        
        Object value = auctionTable.getValueAt(row, 2);
        return String.valueOf(value.toString());
    }
    
    private String getSelectedCurrentBID() {
        int row = auctionTable.getSelectedRow();
        if (row == -1) {
            return "";
        }
        
        Object value = auctionTable.getValueAt(row, 5);
        return String.valueOf(value.toString());
    }
    
    private void loadLelang() {
        JSONObject resp = lelang.getAuctions();
        if (!resp.has("status") || !resp.getBoolean("status")) {
            String message;
            
            if (!resp.getBoolean("status")) {
                message = resp.getString("message");
            } else {
                message = "gagal mengambil data.";
            }
            
            JOptionPane.showMessageDialog(this, message, "gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LelangTable.setRowCount(0);
        
        JSONObject data = resp.getJSONObject("data");
        JSONArray auctions = data.getJSONArray("auctions");
        
        for (int i = 0; i < auctions.length(); i++)
        {
            JSONObject auction = auctions.getJSONObject(i);
            JSONObject item = auction.getJSONObject("item");
            JSONObject user = auction.getJSONObject("user");
            
            int auctionID = auction.getInt("id");
            String ownerItem = user.getString("name");
            String namaItem = item.getString("name");
            String descItem = item.getString("description");
            int startBid = auction.getInt("starting_bid");
            int currentBid = auction.getInt("current_bid");
            int countBid = auction.getInt("bid_count");
            String startTime = lib.timeAgo(auction.getString("start_time"));
            String endTime = lib.timeAgo(auction.getString("end_time"));
            
            Object[] row = {auctionID, ownerItem, namaItem,
            descItem, startBid, currentBid, countBid, startTime, endTime};
            
            LelangTable.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        auctionTable = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnBid = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(660, 450));

        auctionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Owner", "Nama", "Deskripsi", "Start", "Current", "Count", "Start", "End"
            }
        ));
        jScrollPane1.setViewportView(auctionTable);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnBid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-auction-24.png"))); // NOI18N
        btnBid.setText("Tambah BID");
        btnBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBid)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchText)
                    .addComponent(btnBid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String keyword = searchText.getText();
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(LelangTable);
        auctionTable.setRowSorter(sorter);
        
        if (keyword.trim().length() == 0) {
           sorter.setRowFilter(null);
           return;
        }
        
        sorter.setRowFilter(RowFilter.regexFilter("(!?)" + keyword));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidActionPerformed
        // TODO add your handling code here:
        int auctionID = getSelectedID();
        String name = getSelectedName();
        String currentBID = getSelectedCurrentBID();
        
        if (auctionID == -1) {
            JOptionPane.showMessageDialog(this, "tidak ada item yang dipilih", "gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LelangPopUp popoup = new LelangPopUp(auctionID, name, currentBID);
        popoup.setVisible(true);
    }//GEN-LAST:event_btnBidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auctionTable;
    private javax.swing.JToggleButton btnBid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
